### ISSUE TITLE
Can we add the official templates to this app as well as the unofficial ones?

### ISSUE THREAD

**Issue by jamesmortensen** [smattar2020/utm-templates#2]
I was thinking that since the official gallery is simply linking to the release artifacts in the UTM/vm-downloads repo, it would also be possible to add them to this app.  I'd prefer to download the official ones, if what I'm looking for is available already; otherwise, I'd look for a third party VM in a third-party gallery.

This is the URL to the official Debian 10.4 LXDE ARM64 UTM VM, for example:
`https://github.com/utmapp/vm-downloads/releases/download/debian-10.4/debian-10.4-ldxe-arm64-utm.zip`

**Comment by smattar2020** [comment]
I'll get right on it.

**Comment by smattar2020** [comment]
I added a few for now. I will add more later. https://github.com/smattar2020/utm-templates/actions/runs/2242102035

**Comment by smattar2020** [comment]
I added all of the prebuilt official VMs. https://github.com/smattar2020/utm-templates/actions/runs/2245267663

**Comment by smattar2020** [comment]
The functionality here is available as a beta at: https://github.com/smattar2020/utm-templates/releases/tag/v1.1.0-beta1
